name: "CI"

on:
  pull_request:
    branches:
      - main

jobs:
  deps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer

      - name: Cache vendor
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}

      - name: Install Dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

  linter:
    needs: ["deps"]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore Cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}

      - name: Generate cs config
        run: cp phpcs.xml.dist phpcs.xml

      - name: PHP Code Sniffer
        uses: php-actions/phpcs@v1
        with:
          path: src/
          php_version: 8.2
          standard: phpcs.xml

      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v3
        with:
          path: src/
          php_version: 8.2
          level: 9
